#!/bin/sh
# 
### BEGIN INIT INFO
# Provides:          PcapDNSProxyService
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pcap_DNSProxy service
# Description:       A local DNS server base on libpcap.
### END INIT INFO
#


#Defines
NAME=Pcap_DNSProxy
PATH=/home/chengr28/Pcap_DNSProxy
PROGRAM=/sbin/start-stop-daemon
USR=root
START_FLAGS="--start --background --exec"
STOP_FLAGS="--stop --exec"
TIME_OUT="--retry 5"

#Main controller
case "$1" in
start)
	echo "Starting PcapDNSProxyService"
	$PROGRAM $START_FLAGS $PATH/$NAME --chdir $PATH --chuid $USR
	;;
stop)
	echo "Stopping PcapDNSProxyService"
	$PROGRAM $STOP_FLAGS $PATH/$NAME --chuid $USR
	;;
restart)
	echo "Restarting PcapDNSProxyService"
	$PROGRAM $STOP_FLAGS $TIME_OUT $PATH/$NAME --chuid $USR
	$PROGRAM $START_FLAGS $PATH/$NAME --chdir $PATH --chuid $USR
	;;
*)
	echo "Usage: PcapDNSProxyService {start|stop|restart}"
	exit 0
	;;
esac
exit 0
