#!/bin/sh
# 
### BEGIN INIT INFO
# Provides:          PcapDNSProxyService
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pcap_DNSProxy service
# Description:       A local DNS server base on libpcap.
### END INIT INFO
#
# Author:	Chengr28
#


#Defines
NAME=Pcap_DNSProxy
PATH=/home/chengr28/Pcap_DNSProxy
PROGRAM=/sbin/start-stop-daemon
START_FLAGS="--start --background --chuid root --exec"
STOP_FLAGS="--stop --chuid root --exec"

#Main controller
case "$1" in
start)
	echo "Start Pcap_DNSProxy service"
	$PROGRAM $START_FLAGS $PATH/$NAME --chdir $PATH
;;
stop)
	echo "Stop Pcap_DNSProxy service"
	$PROGRAM $STOP_FLAGS $PATH/$NAME
;;
force-reload|restart)
	echo "Force-reload/Restart Pcap_DNSProxy service"
	$PROGRAM $STOP_FLAGS $PATH/$NAME
	$PROGRAM $START_FLAGS $PATH/$NAME --chdir $PATH
;;
status)
	echo
	/bin/ps -C Pcap_DNSProxy
	echo "\nIf PID is empty, Pcap_DNSProxy is not running."
;;
*)
	echo "Usage: PcapDNSProxyService {start|stop|force-reload|restart|status}"
	exit 0
;;
esac
exit 0
